[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_market = "oA1FPmR6KgkAeJ5QsxTgPKzAvzPeUCyF6fNESucurMP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/spaceman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
